# Generated by Django 3.0.3 on 2020-02-26 18:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouttracker', '0005_auto_20200220_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Run'),
        ),
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distance Ran - In km'),
        ),
        migrations.AlterField(
            model_name='run',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Time - In Minutes'),
        ),
        migrations.CreateModel(
            name='DemoManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDemo', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
